# Numpy

1. Numpy stands for Numerical Python
2. Numpy is a Python Library used for working with arrays.
3. It also has Function for working in domain of linear algebra, Fourier transform, matrices

# Why Use Numpy

1. In python we have lists that serve the purpose of arays, but they are slow to process.
2. Numpy aims to provide an array object that is up to 50x faster than traditional Python List.
3. The array object in Numpy is called ndarray.

# Why is Numpy Faster than Lists?

Numpy arrays are at one continuous place in memory Unlike lists, So processes can access and manipulate then very efficiently.

# Install Dependancy

pip install numpy

# If you want to check version

pip show numpy

pip list

In [8]:
import numpy as np

In [9]:
v1 = [10, 20, 30]

print(v1, type(v1))

print('--------------------------------------')

# Single Dimention array

nv1 = np.array(v1)

print(nv1, type(nv1))

[10, 20, 30] <class 'list'>
--------------------------------------
[10 20 30] <class 'numpy.ndarray'>


In [14]:
v2 = [[10, 20, 30], [40, 50, 60]]

print(v2, type(v2))

print('--------------------------------------')

# Two Dimention array

nv2 = np.array([1, 2 ,3])

print(nv2, type(nv2))

[[10, 20, 30], [40, 50, 60]] <class 'list'>
--------------------------------------
[1 2 3] <class 'numpy.ndarray'>


# Arange

In [15]:
av1 = np.arange(0, 10)

print(av1)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
av1 = np.arange(0, 10, 2)

print(av1)

[0 5]


# Linspace

In [30]:
lv1 = np.linspace(0, 10, 100)

print(lv1)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [21]:
lv1 = np.linspace(0, 10, 5, dtype=int)

print(lv1)

[ 0  2  5  7 10]


# RandInt

In [34]:
rnv1 = np.random.randint(1, 10)

print(rnv1)

7


In [42]:
rnv1 = np.random.randint(1, 100, 3)

print(rnv1)

[13 18 32]
