# To Find the Shape

In [1]:
import numpy as np

In [10]:
v1 = np.linspace(1, 10, 6, dtype=int)

print(v1)

print(v1.shape)

[ 1  2  4  6  8 10]
(6,)


# To Change the Shape use reshape method

In [13]:
rV1 = v1.reshape(2, 3)

print(rV1)

print('------------------------------')

print(rV1.shape)

[[ 1  2  4]
 [ 6  8 10]]
------------------------------
(2, 3)


# Indexing & Selection

In [16]:
v1 = np.array([1, 2, 3, 4, 5, 6])

print(v1)

print(v1[1])

print(v1[1:3])

[1 2 3 4 5 6]
2
[2 3]


In [41]:
v1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(v1)

print('-----------------------------------------')

print(v1[0])

print('-----------------------------------------')

print(v1[0][0])

print('-----------------------------------------')

print(v1[1][1]) # v1[row][column]

print('-----------------------------------------')

print(v1[0][0:2])

print('-----------------------------------------')

print(v1[0:3, 0:2]) # v1[row, Column]

print('-----------------------------------------')

print(v1[0:3, 0])

print('-----------------------------------------')

print(v1[0][0], v1[1][1], v1[2][2])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------------------------------
[1 2 3]
-----------------------------------------
1
-----------------------------------------
5
-----------------------------------------
[1 2]
-----------------------------------------
[[1 2]
 [4 5]
 [7 8]]
-----------------------------------------
[1 4 7]
-----------------------------------------
1 5 9


In [42]:
print('-----------------------------------------')

print(v1[1][1]) # v1[row][column]

-----------------------------------------
5


In [43]:
print('-----------------------------------------')

print(v1[0:3, 0:2]) # v1[row, Column]

-----------------------------------------
[[1 2]
 [4 5]
 [7 8]]


In [59]:
# Slicing USing Condition

rV1 = np.random.randint(1, 100, 30)

print(rV1)

[ 7 83 51 41 62 48 48 73 61 60  5 82  8 23  3 33 25 58 71 58 79 53 53 83
 41 23 81 11 81 67]


In [60]:

a = rV1 > 18

print(a)

[False  True  True  True  True  True  True  True  True  True False  True
 False  True False  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True]


In [61]:
print(rV1[a])

[83 51 41 62 48 48 73 61 60 82 23 33 25 58 71 58 79 53 53 83 41 23 81 81
 67]
