# Copy Data

In [1]:
import numpy as np

In [3]:
v1 = np.linspace(1, 50, 8, dtype=int)

print(v1)

[ 1  8 15 22 29 36 43 50]


In [4]:
v1Copy = v1.copy()

print(v1Copy)

[ 1  8 15 22 29 36 43 50]


In [8]:
print(v1[2])

print(v1[2:6])

print('----------------------------------')

v1[2] = 20

v1[3:6] = 25

print('----------------------------------')

print(v1)

25
[25 25 25 25]
----------------------------------
----------------------------------
[ 1  8 20 25 25 25 43 50]


In [9]:
print(v1Copy)

[ 1  8 15 22 29 36 43 50]


# Using Arithmatic Operations on Arrays

In [11]:
v1 = np.array([10, 20, 30, 40])

print(v1)

print('------------------------------------')

print(v1 + 2)

[10 20 30 40]
------------------------------------
[12 22 32 42]


In [13]:
v2 = np.array([[10, 20], [30, 40]])

print(v2)

print('------------------------------------------------')

print(v2 + 2)

[[10 20]
 [30 40]]
------------------------------------------------
[[12 22]
 [32 42]]


In [15]:
v1 = np.array([[1, 2], [3, 4]])


aV1 = v1 + v2

print(aV1)

[[11 22]
 [33 44]]


# min, max, argmin, argmax

In [16]:
v1 = np.random.randint(1, 20, 10)

print(v1)

[13  4 15  2  8 19 15  9  6  6]


In [18]:
print(v1.min())

print(v1.max())

2
19


In [19]:
print(v1.argmin())

print(v1.argmax())

3
5


In [20]:
print(v1.sum())

97


In [25]:
print(np.median(v1))

8.5
