# Python Numpy Read and Write Files

In [1]:
import numpy as np

In [2]:
v1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(v1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Create and Write Files

np.savetxt('test.txt', v1)

In [4]:
# Read File 

rV1 = np.loadtxt('test.txt')

print(rV1)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
